# Generated by Django 5.2 on 2025-04-24 00:09

import Money_Parse.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money_Parse', '0010_income_delete_incomes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exspenses',
            name='user',
            field=models.ForeignKey(default=Money_Parse.models.get_unnamed_user, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
